# Generated by Django 6.0 on 2026-02-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_response',
        ),
    ]
