# Generated by Django 6.0 on 2026-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('service', 'Service'), ('technical', 'Technical'), ('other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
